### ISSUE TITLE
Have a "base" model we can easily change architecture in a script that also uses Python's argparse

### ISSUE THREAD

**Issue by Daniel8hen** [scancer-org/ml-pcam-classification#2]
In a nutshell, try to have a "base" model that we can easily change its architecture in a script + try to integrate command line for params like in lab 5

**Comment by Daniel8hen** [comment]
We have an architecture we can play with using a script I created called "cnn_model". Has some nice hyperparameters, e.g. stride, padding, conv size, etc.

**Comment by hnarayanan** [comment]
Really good.
